services:
  db:
    image: postgres:16-alpine
    container_name: custom-orm-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: CUSTOM-ORM
    ports:
      - "5432:5432"
    volumes:
      - custom-orm-pgdata:/var/lib/postgresql/data

volumes:
  custom-orm-pgdata:
